from __future__ import annotations


PRESETS: dict[str, dict[str, object]] = {
    "debug": {
        "limit": 2000,
        "max_source_len": 12,
        "max_target_len": 12,
        "max_vocab_size": 12000,
        "batch_size": 64,
        "epochs": 2,
        "embedding_dim": 64,
        "encoder_hidden_dim": 128,
        "decoder_hidden_dim": 128,
        "dropout": 0.2,
        "optimizer": "adam",
        "lr": 1e-3,
        "teacher_forcing_ratio": 0.5,
        "sort_k_batches": 10,
        "readout": "maxout",
        "tokenizer": "legacy",
    },
    "tutorial": {
        "limit": 12000,
        "max_source_len": 20,
        "max_target_len": 20,
        "max_vocab_size": 12000,
        "batch_size": 64,
        "epochs": 10,
        "embedding_dim": 128,
        "encoder_hidden_dim": 256,
        "decoder_hidden_dim": 256,
        "dropout": 0.2,
        "optimizer": "adam",
        "lr": 1e-3,
        "teacher_forcing_ratio": 0.5,
        "sort_k_batches": 10,
        "readout": "maxout",
        "tokenizer": "legacy",
    },
    "paper": {
        "limit": None,
        "max_source_len": 50,
        "max_target_len": 50,
        "max_vocab_size": 30000,
        "batch_size": 80,
        "epochs": 20,
        "embedding_dim": 620,
        "encoder_hidden_dim": 1000,
        "decoder_hidden_dim": 1000,
        "dropout": 0.0,
        "optimizer": "adadelta",
        "lr": 1.0,
        "teacher_forcing_ratio": 1.0,
        "sort_k_batches": 20,
        "readout": "maxout",
        "tokenizer": "whitespace",
    },
    "rtx5090": {
        "limit": None,
        "max_source_len": 50,
        "max_target_len": 50,
        "max_vocab_size": 30000,
        "batch_size": 160,
        "epochs": 20,
        "embedding_dim": 620,
        "encoder_hidden_dim": 1000,
        "decoder_hidden_dim": 1000,
        "dropout": 0.0,
        "optimizer": "adadelta",
        "lr": 1.0,
        "teacher_forcing_ratio": 1.0,
        "sort_k_batches": 20,
        "readout": "maxout",
        "tokenizer": "whitespace",
    },
}
